### ISSUE TITLE
Support for CGmap inputs

### ISSUE THREAD

**Issue by harish0201** [hhg7/defiant#5]
Hi Dave!

I have recently come across cgmaptools which is a host of tools that can be used to call methylation and other analysis like allele specific methylation, snv calling etc. 

The cgmap output can be derived from either post-processing the aligned bams or is one of the outputs from BS-Seeker. 

The format as such looks like this:

> chr1    G   3000851   CHH   CC  0.1   1   10
> chr1    C   3001624   CHG   CA  0.0   0   9
> chr1    C   3001631   CG    CG  1.0   5   5
> chr1    G   3001632   CG    CG  0.9   9   10

Where the headers are: 

Chromosome Reference_Nucleotide Position Context_Type Context Methylation_Status Methylated_Cyto_Counts Total_Cyto_Counts

The format as such seems to be similar to Bismark's format 5 as per the Readme. 

Would it be possible for you to support it?

**Comment by hhg7** [comment]
Hi @harish0201 

sure, I'll get working on that for the next version, I'll update you soon!

**Comment by hhg7** [comment]
Hi @harish0201 

I updated Defiant so it now reads CGmap input.  Please let me know if it works for you.

**Comment by harish0201** [comment]
Alright! Thanks for the update. 

I'll check it now.

**Comment by harish0201** [comment]
Hi Dave!

I'm working on the inputs, but they seem to crash on the wheat genome, I'll parse them out chromosome wise and get back to you. It seems to give me a CRC error on gzipped files though gunzipping them seems to work.

**Comment by hhg7** [comment]
Hi Harish,

Defiant only reads regular ASCII files.  I've considered making it to read gz, but I don't know how yet. Please let me know how everything works out.

**Comment by harish0201** [comment]
Will do!

In the mean time, may be trying to use the system calls (zcat or pigz -c) should be better in order to read compressed files!

However, I'm facing no issues running on the unzipped files though, so it's all good :)

Edit: Duplicate Comment

**Comment by harish0201** [comment]
Will do!

In the mean time, may be trying to use the system calls (zcat or pigz -c) should be better in order to read compressed files!

**Comment by hhg7** [comment]
Did everything work out? I'd like to close the issue.

**Comment by harish0201** [comment]
Yup, it seems to have the trick! Sorry I was travelling a bit, so I wasn't able to do. it.

BTW, would you be at the PAG? I would to have a chat with you.

**Comment by hhg7** [comment]
@harish0201  unfortunately, no, but I would have applied had I known about the conference.

**Comment by hhg7** [comment]
My email is dec986@gmail.com if you have any questions, or would like to chat.
